variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_CLEAN_FLAGS: none

# Building using debototstrap, chroot requires root access, following changes needs to
# be added using 'sudo visudo'
# gitlab-runner ALL=(ALL) NOPASSWD: /usr/bin/make, /usr/bin/cp, /usr/bin/rm

stages:
- build

.build-package:
  stage: build
  script:
    - sudo make clean PROFILE=${PROFILE_NAME}
    - sudo make image PROFILE=${PROFILE_NAME}
    - sudo make package PROFILE=${PROFILE_NAME}
    - sudo chown -R gitlab-runner:root build-${PROFILE_NAME}/package/
  artifacts:
    paths:
      - build-${PROFILE_NAME}/package/
    expire_in: 30d
  tags:
    - yeti


build-kstr-sama5d27:
  extends: .build-package
  variables:
    PROFILE_NAME: kstr-sama5d27

build-whle-ls1046a:
  extends: .build-package
  variables:
    PROFILE_NAME: whle-ls1046a

build-whle-ls1088a:
  extends: .build-package
  variables:
    PROFILE_NAME: whle-ls1088a

build-rchd-pf:
  extends: .build-package
  when: manual
  variables:
    PROFILE_NAME: rchd-pf
